### ISSUE TITLE
Clean Up

### ISSUE THREAD

**Issue by Gr770** [Gr770/CK3-Community-Title-Project#3]
Once Ruler Titles are done, I need to scrub and filter out duplicates for optimization.

**Comment by Charanraja123** [comment]
I already created a branch for this. This doesn't remove titles that are already present in the ck3 game folder. I did not do that comparison. We can do that after adding Ruler Titles as you suggested above.

The master file somehow doubled and appended to itself. I removed all the duplicates (one half of the file content almost). I made my best to make sure to cross verify that I did not delete any new additions to the code. I suggest we sort this problem now as my branch edit the upper duplicates while the existing ones were in the lower. We can then ask everyone to rebase their files so we dont compound this problems further.

**Comment by Charanraja123** [comment]
> 
> 
> I already created a branch for this. This doesn't remove titles that are already present in the ck3 game folder. I did not do that comparison. We can do that after adding Ruler Titles as you suggested above.
> 
> The master file somehow doubled and appended to itself. I removed all the duplicates (one half of the file content almost). I made my best to make sure to cross verify that I did not delete any new additions to the code. I suggest we sort this problem now as my branch edit the upper duplicates while the existing ones were in the lower. We can then ask everyone to rebase their files so we dont compound this problems further.

This has been resolved

**Comment by Gr770** [comment]
I mean duplicates like cultures sharing the same word. Just a scrub thru would be fine at the end.

**Comment by Charanraja123** [comment]
Ive went through and removed all vanilla folder details present in our mod. Check and let me know

**Comment by Gr770** [comment]
Resolved
