### ISSUE TITLE
Pull Request Optimisation

### ISSUE THREAD

**Issue by Charanraja123** [Gr770/CK3-Community-Title-Project#36]
We are now five people working on the project and I think some set procedures/rules would be helpful to make sure we don't waste too much time fixing merging conflicts. Here is what I suggest.

- Having one Fixes type pull request open at all times. Everyone can make commits to it. Since Gib(Gr770) is the only one merging having him open the pull request again every time he merges would be perfect. This would make sure that fixes don't break merging which might happen if we all open individual pull requests for them.  

- The next type of pull request is the Additions one which as it suggests is adding new cultures/bookmarks etc. The point being that additions should not modify anything already present in the master branch but add upon it in any way possible. This means we can have multiple Additions type pull requests open, which we just re-base and merge without any conflicts (as they do not in any way modify each other or the master branch)

- The last is the overhaul/cleanup type request which can change the whole master branch file structure. Ideally, we need to merge these at a time when there are no Additions/Fix changes pending, so that we don't ruin any ones work. Considering that these will be few and far between we need not worry about it too much now.

Hopefully I did not come across as too nitpicky. I just wanted to make sure we all can work on the project in a more focused manner without worrying about the conflicts.

**Comment by Gr770** [comment]
Fix branch open.

**Comment by Charanraja123** [comment]
I've edited the Wiki To include these rules

**Comment by Viridianus** [comment]
Fix branch needs to be reopened, I suppose - or are you waiting for a first actual fix?

**Comment by Charanraja123** [comment]
Let Gib come and do that because I;m kinda done for the day

**Comment by Gr770** [comment]
You have to make a change to make a request. Ill end up with a dummy file like last time
