### ISSUE TITLE
Marches and Palatinates

### ISSUE THREAD

**Issue by Gr770** [Gr770/CK3-Community-Title-Project#37]
Keeping this here to check on custom localization or paradox adding flags

**Comment by Charanraja123** [comment]
Update: Since we got custom loc to work on stuff. I'm going take another shot at making this work. Lets see what pans out.

**Comment by Gr770** [comment]
I gave it a try and I got blank spaces.

**Comment by Gr770** [comment]
Testing notes

`DukeType = {
	type = character
	text = {
		trigger = {
			has_culture = anglo_saxon
			has_character_flag = is_march ##added add_character_flag to vassal contract
		}
		localization_key = marquess_anglo_saxon
	}
	text = {
		localization_key = duke_default
		fallback = yes
	}
}`

`duke_male_anglo_saxon:0 "[ROOT.Char.Custom('DukeType')]"`

Anything look off?

**Comment by Charanraja123** [comment]
Nothing looks off. Usually blank stuff are scope errors. 
Question, does the liege have the flag or the vassal.? That can confuse things

**Comment by Gr770** [comment]
Actually I should use vassal_contract_has_flag = has_march_contract as it's built in. It's labeled as a character flag and should be for the root character.

**Comment by Charanraja123** [comment]
Yes, That was exactly what confused me, Then I thought maybe something was wrong with that flag.
From what I saw in the files, The flag is affixed to the vassal and not the liege, which is a good thing. 

Everything said, something is wrong with your calling, since blank means it doesn't even go to default.

**Comment by Charanraja123** [comment]
try 
`Character.Custom` , or any other scope and see which works

**Comment by Gr770** [comment]
Holy moly, I got it!

`[CHARACTER.Custom('DukeType')]` works!

Just got to get it to say Marquess or Duke now.

**Comment by Charanraja123** [comment]
Good job man!.
Does it work for the titles too? like Marches and Palatinates. I think you have to change the scope scope:holder or something similar, since the flags are attached to the character

**Comment by Charanraja123** [comment]
On a side note (Or maybe a main one), We would have to re-structure a lot to make this work in flavorisation, I'll try and see if I can come up with a proper system for it. Especially this also means that we can do Grand duchies too.
@Gr770 Could you pull up a branch 'Possible Titles' and upload the stuff you have been working on.

**Comment by Gr770** [comment]
It's literally just a test file.
