### ISSUE TITLE
Independent Ruler Domain Holdings

### ISSUE THREAD

**Issue by Charanraja123** [Gr770/CK3-Community-Title-Project#38]
Domains under Independent rulers are considered independent which should not be the case. Solution yet to be found for this

**Comment by Viridianus** [comment]
Note that this means, in particular, that, unless we _want_ the independent county title to be used in such context (for some cultures we actually do or at least can live with it, like Gaelic or Slavic), we should not code it in.

**Comment by Charanraja123** [comment]
I disagree. This is bug and sometimes bugs are there. It becomes very cumbersome to move everything around it. 

Unfortunately, For time being this is as it is. I'll try to fix this later (I have some Ideas) but a bug should not encourage the removal of any entry unless it breaks the game in some way (Not immersion wise, Actually crash or create some big errors).
We will put a disclaimer in the Steam page about it.
Until someone of us comes up with a fix (Me or anyone else) or Paradox fixes it, The best course of action is to acknowledge it to the users and then forget it.

**Comment by Viridianus** [comment]
Principaltes throughout England really kill the mood though... maybe at least clear up the remains from when the rows weren't split?

**Comment by Charanraja123** [comment]
I don't quite understand, Didn't we just clean up English in the fixes?

**Comment by Viridianus** [comment]
English - probably, but that's probably throughout the map; I'd say it would be cleaner if we now commented out all of the `count(y)_..._independent` outside Britain, France and East Slavs and then uncommented them as we go through groups.

**Comment by Charanraja123** [comment]
Personally, I don't really think its an issue that needs immediate addressing. We can fix things as we go. After all, we are still in development, so such things are understandable. 
But if it really bothers you that much, You can go ahead and do it.

**Comment by Viridianus** [comment]
By the way, what does `top_liege = no` do? Says you should use your culture not your top liege's?

**Comment by Charanraja123** [comment]
Exactly that, the conditions check against the root character instead of his top_liege
