### ISSUE TITLE
Priority Outliers in Paradox Vanilla Files

### ISSUE THREAD

**Issue by Charanraja123** [Gr770/CK3-Community-Title-Project#40]
The following have incorrect priority values which can potentially cause problems for our mods.
    duke_feudal_female_hausan_independent
    count_feudal_female_hausan_independent
    count_feudal_male_norse
    count_feudal_female_norse
    county_feudal_norse

I suggest defining them with the same key and definition in our mod folder, but changing the priority to standard values.

**Comment by Viridianus** [comment]
Have you also reported them to Pdx bug reports?

**Comment by Charanraja123** [comment]
I Personally have not, since they do not affect vanilla game play in any manner as far as I know.  I do not know if it is considered a bug, when the intended function only breaks with the inclusion of external mods. So i was hesitant to report them

**Comment by Gr770** [comment]
The norse strings are defined as only for duchies as well.

**Comment by Charanraja123** [comment]
Oh yeah. I'm sorry, I did not notice that. I'll open a ticket and list out these errors.

**Comment by Viridianus** [comment]
So, have we redefined them already? If not, what stops us from doing so and closing this issue?

(Oh, and also: @Charanraja123 - could you share the link to your bug report?)

**Comment by Charanraja123** [comment]
https://forum.paradoxplaza.com/forum/threads/ck-iii-ck3-flavorization-incorrect-definitions.1425784/

I was waiting for the patch to drop. In case they address the things by themselves

**Comment by Viridianus** [comment]
If they do, we close this issue; what do we do if they don't?

**Comment by Charanraja123** [comment]
> I suggest defining them with the same key and definition in our mod folder, but changing the priority to standard values.

This

**Comment by Viridianus** [comment]
I thought we'd already done that... I meant with this issue - will it take the place on the Issues tab until the end of time?)
Also, it seems the patch has dropped fifteen minutes ago - I wanted to copy the old version of 00_landed_titles.txt, but it's already changed.

**Comment by Charanraja123** [comment]
I just started downloading it. I'll fix this and the new landed titles.txt within a couple of hours. I'm kinda pre occupied now, sorry/

**Comment by Viridianus** [comment]
I think I'll manage somehow ;) Since it's save-compatible, it should mean that map hasn't changed - i.e. the set of baronies is the same. This simplifies the issue.

**Comment by Viridianus** [comment]
I think I'll manage somehow ;) Since it's save-compatible, it should mean that map hasn't changed - i.e. the set of baronies is the same. This simplifies the issue.

**Comment by Viridianus** [comment]
A-and... just in case you wondered: it has _not_ been fixed.

**Comment by Charanraja123** [comment]
Oh thanks. Saved me some time :)

**Comment by Charanraja123** [comment]
Made a commit to Master- Fixes branch Clearing this up.
 Once merged I think we can close this
