### ISSUE TITLE
only_ruler condition usage

### ISSUE THREAD

**Issue by Charanraja123** [Gr770/CK3-Community-Title-Project#42]
So, I think the usage of only_ruler should be reviewed. It is used in an arbitrary manner from what I checked (might be wrong).
The only reason to use only_holder is when you do not want to apply to title to the holder consort. For example you can make a empress of Italy unique by giving her definition the only_holder condition. So that any consort of an emperor of Italy does not use that. Hopefully I'm making sense here.

Am I missing any other reason to use this condition?

**Comment by Gr770** [comment]
That should be the only reason to use it. We should only be using it for mayors (not "real" nobles) and if it is defined as different on the google sheet like Eorlwif.

**Comment by Charanraja123** [comment]
OK. 
So basically, for non real nobles like "mayors" and maybe chruch_holders too when we do religion.
Also used when consort is defined differently from the default gender title.
I'll link the fixes pull request here and start working on making sure this is applied properly throughout.
Thanks
