### ISSUE TITLE
Handling different governments.

### ISSUE THREAD

**Issue by Charanraja123** [Gr770/CK3-Community-Title-Project#43]
This issue is basically to call out a discussion on how to handle 

- Clan governments

~~- Theocratic governments~~

~~- Holy Order and Mercenary governments (Do not know if this matters)~~
Please feel free to comment anything that might contribute to discussion. 
If you feel we might have missed out on any order form of holding/title type. Let me know and I'll include it in the description.

**Comment by Charanraja123** [comment]
I personally suggest adding them with feudal as I have never encountered any instance where they might be different till now

**Comment by Gr770** [comment]
Theocracies are to be done with the rest of the religious titles.

**Comment by Viridianus** [comment]
I don't see any difference between clan and feudal which isn't also governed by religion; it is then a question of what is primary.

I think mercs and HOs only lease land not hold it in CKIII? Or am I wrong?

**Comment by Charanraja123** [comment]
What do you mean by "primary" ? 
I just included mercs and HO just to cover all bases. Most likely should not matter.

**Comment by Viridianus** [comment]
I mean that it currently seems we can either code
government = { feudal_government clan_government } religion = { islam_religion }
or
government = { clan_government }.
What's the difference gonna be, assuming tribal is not in?

**Comment by Gr770** [comment]
If you convert to islam as a feudal character, you stay feudal.

**Comment by Charanraja123** [comment]
The solution is to include feudal wherever clan is and vice versa. The difference between these two isn't defined (too murky) for us to assign certain titles to clan while others to feudal. Also the fact the changing from feudal to clan or vice versa is almost impossible according to the forums, means restricting it to one or other will cause the mod to skip over lot of intended flavorisations

**Comment by Viridianus** [comment]
Also related: https://forum.paradoxplaza.com/forum/threads/arabic-lands-names-issue.1426012/ - we'll probably need to clear the line in government file if we don't want (vanilla) Pdx over our holding names.

**Comment by Charanraja123** [comment]
The question is, do we want to edit the government file? This will cause an incompatibility with mods that use that. I suggest we let it be for the time being and come back to discuss this point once we have come out of alpha version

**Comment by Viridianus** [comment]
General solution achieved, the editing of government file is, strictly speaking, a separate and remote issue (though a simple one code-wise: only a single string should be changed from `dynasty_title_names = yes` to `dynasty_title_names = no`). Thus I'm closing this issue.
