### ISSUE TITLE
Multi-culture titles

### ISSUE THREAD

**Issue by Viridianus** [Gr770/CK3-Community-Title-Project#44]
I have noticed that, to save some resources probably, we use a single localization line for several cultures (of the same culture group?) in 00_CTP.
1)Is it even good coding? I mean, we could change it in master sheet for one culture but not for the other, and we'll have to change both 00_CTP and the titles file.
2)If we do use it, shouldn't it have a special name (like _northmen for swedish & danish)? An example of not doing it is here:
https://github.com/Gr770/CK3-Community-Title-Project/blob/55ad852468329ede090664b443e91c6ac7686a3a/common/flavorization/00_CTP.txt#L3313
king_male_finnish ("Kuningas") is used for Finnish, Estonian, and Karelian. It's not the entirety of Balto-Finnic, so "king_male_balto-finnic_group" is out; but shouldn't we create a special name here like, say, "king_male_finnic"?

**Comment by Charanraja123** [comment]
Here's my 2 cents.
If the cultures form the majority of the cultural group, just use the cultural group name. The rest of the cultures can be defined as outliers.
If the culture are from the same group but are not the majority, you can define something like king_male_finnish_estonian_karaliean. This is acceptable. The main point being the name should give us enough information at a glance (aspects of good coding).
If they are from different group, do not define them together, We can see  some in our mod i think, but i was planning on cleaning them later. The reason I'm against this is that, this breaks our own convention/system of group organizing titles by culture group. It also makes priority checking so much more harder.

All that being said, not following these standards will not not break the code in any way. It;ll just make checking, debugging and feature additions all that more hard in the future.

**Comment by Viridianus** [comment]
That kinda answers my second question (though I would go against "just use the cultural group for majority" as this also complicates checking). What do you think on the first one - i.e. on the alternative of not using combined titles at all to simplify editing?

**Comment by Charanraja123** [comment]
We certainly can. We just have to make sure we track/keep a list of those special names. Even adding a comment below that first time it comes up will do. I would rather just enter everything at the top of the file (sort of like an index). Everything in comments obviously. Yours does look more elegantly but please keep in mind to not add too much special titles. There is no hard limit per se, lets say just not more than 10 would be fair.

**Comment by palfourti** [comment]
To you first point it just seems like a choice between whether you want to add entry for a cultural title now or later. The way we're doing it now is messy and probably not professional but it definitely saves time on updating the mod (which may have to be repaid later of course).

**Comment by Charanraja123** [comment]
@palfourti As you say, it is a tradeoff. It depends on whether we want to get our mod out there, or we want to give out a much more optimised/stabilised mod.(FYI, flavorizations are super stable in CK3, basically they never cause a crash) 
Considering that 90 percent of our mod users are not going to look into these files. Maybe we should just focus on covering as much titles as we can, and clean up later. 
Or we can do something like, we take a single cultural group every week and clean it up through the Master-Fix branch, while continuing to add titles in as fast as we can.
It's our call.

**Comment by Viridianus** [comment]
Clean up helps 1)us and 2)optimization; of course it does not help end users directly.
What we do may indeed cause repayment later with editing.

I kinda thought we add titles and fix them in a similar pace?

**Comment by Charanraja123** [comment]
> I kinda thought we add titles and fix them in a similar pace?
It was never discussed in the forum, but since we all are on the same page here, Lets take that approach. 

Coming back to your problem, here's the proposed solution, It has worked so far for me.

- If there is one repeating title shared among cultural the group, you just define it by the cultural group. Looks like this
```
something_<culture_group>_ = {
....
culture_groups = <culture_group>
}
something_<culture1> = {
.....
cultures = <culture1>
}
```
- If there are more than two distinct repeating title in the same culture group, use this. The numbers can be however high you want it to be
```
something_<culture_group>_1 = {
....
cultures = {<culture1>,<culture2>..}
}
something_<culture_group>_2 = {
....
cultures = {<culture3>,<culture4>..}
}
something_<culture5> = {
.....
cultures = <culture5>
}
```

- If there is names shared across culture group do not group them. If they are already group, we should be splitting them when cleaning up.
This system should work for whatever title grouping you may come across

**Comment by Viridianus** [comment]
So you suggest that if we have three Balto-Finnic titles, one for Veps, one for Saami and one for the rest, the last one should be called _balto-finnic_group.

**Comment by Charanraja123** [comment]
All my comments were specifically meant for instances were there were repetition of titles.
>  So you suggest that if we have three Balto-Finnic titles, one for Veps, one for Saami and one for the rest, the last one should be 
> called _balto-finnic_group.

If there are three cultures only, you can definitely use the `_culture3_` instead of `_balto_finnic_group`

**Comment by Viridianus** [comment]
No, no, there are five cultures in the group overall (as you may have deduced). I am not sure 3 of 5 _should_ qualify, but by the letter of what you've written it does.

(And, more disturbingly, even Serbian/Bosnian titles seem to qualify for southern_slavic, too - but those are clearly to be just called Serbian if they're not shared with something else, as they are Serbian).

**Comment by Charanraja123** [comment]
In short, Yes. it should qualify.

It is not as much qualification,  as it is more like overriding. I'll explain. Idk if you read the priority system I outlined in the wiki, basically culture_group has less priority value than specific cultures by 1 (unless some other condition also changes). This means that every culture in that culture group would qualify for culture group localization. But when it comes to, lets say specific cultures that you defined, the new culture definition will override the old culture group one since this has a higher priority.

It's like having a blanket default and then specializing wherever needed.

**Comment by Viridianus** [comment]
Aha. I kinda thought this could be the case.

In the light of this, I request permission for deleting everything _bosnian in 00_CTP (and, accordingly, in localization files) and marking everything with _serbian as cultures = { serbian bosnian } instead. @palfourti @Gr770 If there are some differences now, there should not be (the culture name is not contained in 00_CTP).

**Comment by Gr770** [comment]
Go ahead, or I can do it after work.

**Comment by Viridianus** [comment]
I think the result of our discussion should be put in the wiki; after that, this issue can be closed.

**Comment by Charanraja123** [comment]
Yes. I'll do it today or latest by tomorrow.

**Comment by Charanraja123** [comment]
I've added everything I could think of in the wiki. Hopefully it is understandable enough, You can close this issue after checking whether that explanation has no issue.

**Comment by Viridianus** [comment]
I checked it out and edited a teeny-tiny bit, looks OK now.

**Comment by Viridianus** [comment]
I left some extensive comments (Master-Fixes branch, ofc) in 00_CTP on titles which currently either violate our convention or are otherwise really counterintuitive (like basque+aragonese empress). Someone will have to go through and do something about it, and it won't be me.

**Comment by Charanraja123** [comment]
As I said in some other thread (too much of them to keep track lol), I'll be cleaning up extensively culture by culture, to make sure everything falls right as I listed out in the wiki. It might take some time, but I'm kinda particular when it comes to naming conventions in coding, priority numbers are also dangerous in a way, if not kept properly can fuck things up. So I'll do it. I'll close this one and open another, for purposes I'll explain there
