### ISSUE TITLE
Coptic

### ISSUE THREAD

**Issue by Viridianus** [Gr770/CK3-Community-Title-Project#46]
I found that the file now suggests special localizations for Egyptian culture with Coptic religion. Is it really the optimal way to implement Coptic?
And the question is two-fold:
1)Maybe we should restrict it to mods adding Coptic culture, which there will be?
2)If not, maybe we should extend it to Christians more generally? I doubt Armenian or Orthodox faith would be more Arabic than Coptic.

**Comment by Charanraja123** [comment]
1) I have no idea how to do that.
2) I dont exactly understand what you mean by extending it further, do you mean changing Egyptian_coptic to Egyptian_orthodox_coptic. Or do you mean using egyptian_coptic titles for arabian_coptic_orthodox.

**Comment by Gr770** [comment]
1. Not right now.

2. He means changing it to religions = { christian_religion }

**Comment by Charanraja123** [comment]
2. I have no idea whether those titles extended to Arabic christian rulers. If they do, we can certainly add that.

**Comment by Viridianus** [comment]
I mean, the titles are currently _emulating_ Coptic culture via religion. It's not like there's much historical accuracy either way if 1 is correct.

**Comment by Charanraja123** [comment]
Why don't we discuss this in the forum with other people who are much much versed in history/language than me. I have absolutely no idea how to judge this. Sorry

**Comment by Gr770** [comment]
Closing as this is more of an forum issue.
