### ISSUE TITLE
Principalities/Petty Kingdoms

### ISSUE THREAD

**Issue by Gr770** [Gr770/CK3-Community-Title-Project#50]
Master Fixes needs a pass through for cleaning up cultures that wouldn't have principalities but instead just called themselves king.

**Comment by Charanraja123** [comment]
Quick question, would it be fair to assume that anyone outside of HRE called themselves Petty King while only those inside used the terms Prince?
In that someone should also go through the sheet to make sure there aren't cultures who used princes when they should be using petty king instead (Since we just added it)

**Comment by Gr770** [comment]
I believe they would have called themselves princes outside of the HRE as well.

Petty Kingdoms was more of an England, Irish, and Scandinavian thing.


I should add. Irish already has petty kingdoms built in as they all call themselves some form of Ri.

**Comment by Charanraja123** [comment]
What about for entries other than Northern Europe and HRE, like Arabic, Chinese etc?. Should we review them on culture to culture basis?

**Comment by Gr770** [comment]
Yes, unfortunately.

The difference between petty kingdoms and principalities are subtle. Regions had one or the other.

**Comment by Gr770** [comment]
Kinda like how there is grand duchies in western Europe and grand duchies in eastern Europe that aren't excatly the same thing

**Comment by Charanraja123** [comment]
Okay Noted. I have a suggestion based on this, which I'll put it in the Release Version question Issue, so that I don't talk off topic here.

**Comment by Viridianus** [comment]
Oh, that's gonna be fun. Britannia has a lot of Princes - I edited it out for Goidelic in the sheet as that was thankfully yellow, but West Germanic claims its "Princes" to be already coded.

**Comment by Charanraja123** [comment]
@Viridianus I am anyway going to be cleaning up culture groups one by one . At that point I'll request a review from you and we can edit that. If my idea feels more comfortable, We can combine this with the clean up.

**Comment by Viridianus** [comment]
Included in the general clean-up: #57
