### ISSUE TITLE
Release Version Plans

### ISSUE THREAD

**Issue by Charanraja123** [Gr770/CK3-Community-Title-Project#51]
I know this isn't a pressing issue, but I'm curious as to after modding what files does alpha end?

**Comment by Gr770** [comment]
Once the culture groups that are 'completed' are in.  We wouldn't have to make constant updates.

**Comment by Charanraja123** [comment]
This is maybe way in the future, but I think we are close to release version, Hence this comment.

I do have some suggestion on releasing our First version (maybe after things settle down). I am just putting these out there early, so they we can discuss it leisurely.

A weekly cultures/culture group thread. I'll list out the reasons below.
1. I gave it a weeks time as it allows for in depth discussion in a semi-leisurely pace considering there would more of us discussing said culture.
2. I chose the Forum for the platform as it provides more expression and clarity to a discussion than what could be achieved in a google sheet.
3. The discussion can vary from Main titles, Etb, Religious titles to Modding formats. So it does help a lot for all of us to focus and sort/Improve things out.
4. I included the Main sheet because I still think there are stuff to be built upon it. Especially the influence of other cultures/religion towards titles. I got this idea from this [forum post] (https://forum.paradoxplaza.com/forum/threads/ck3-culture-mod-request-thread.1423994/post-26954411), I think he/she explains it aptly. This would be amazing but also would take time.
5. Discussion a specific culture/culture group for a week also means that those who are interested/knowledgeable in that domain can involve themselves in depth for that time period, instead of always/daily being around the sheet for corrections.

Let me know what you guys think. Now let me get to modding in some cultures xD.

**Comment by Gr770** [comment]
I'm good with discussions, especially starting with the cultures not in the sheet.

**Comment by Viridianus** [comment]
I think that won't work because either no one has anything to say on an African or other strange culture or they'll say it anyway.

**Comment by Charanraja123** [comment]
I wanted it for depth dive of European cultures, Like the forum post suggested, how would the titles look if the norse colonised or settled in Ireland and were asatru kind of things (very alt history, but interesting none the less). But i understood it was experimental and had chances of not being successful

**Comment by Gr770** [comment]
There is someone making contributions for the Berbers

**Comment by Viridianus** [comment]
@Gr770: And you believe this is not a coincidence?)

@Charanraja123: I mean, we are supposed to have Norse titles for most of British Isles (even if reconstructed somewhat).

**Comment by Charanraja123** [comment]
@Gr770 I believe the apt word for you to use, as the famous Captain Holt once proclaimed, is "Vindication" xP

@Viridianus You misunderstand me, I mean applying the same concept across a lot of cultures, i used the Norse as an example. "What happens if in the game, the Norse never even reach Ireland, do our titles still make that much sense ?" is an apt example of my line of questioning. Also, would be one of the main end goals of this mod for me. I think no one has done such detailed dynamic titling before (even in CK2, due to the modding restrictions of that game). Maybe this is too ambitious, but it never hurts to dream xD

**Comment by Gr770** [comment]
@Viridianus It could be a coincidence, but placing the weekly focus on the forum's title is a better advertisement for help than just posting just on the thread. Even with European titles, we should see a boost.

**Comment by Gr770** [comment]
It might be a better idea to change focus between those cultures that need it and those cultures that are popular. 

Next week week I can place norse as the culture group and we will probably see an uptick on engagement. If we are in agreement of course.

**Comment by Charanraja123** [comment]
Honestly, spending few mins a week to create a post and follow it for possible entries/ corrections in the sheet sounds quite good . Even if all that happens is discussion with the community (most probably our end users) it is still a positive. If totally nothing comes of it, we don't have any downside. So i say go for it.

**Comment by Charanraja123** [comment]
Change Weekly Focus?

**Comment by Viridianus** [comment]
Yep, we probably should... to what, though? Germanic guys since we started?

**Comment by Charanraja123** [comment]
Deprecated
