### ISSUE TITLE
Relevant Patch Notes

### ISSUE THREAD

**Issue by Charanraja123** [Gr770/CK3-Community-Title-Project#58]
These are whatever relevant I could find, in that realllllllllly long list of changes.

Re-named the 'West African' culture group to 'Guinean' 
Renamed the Wendish Empire to the Southern Baltic Empire 

Add console command to dump out landed title hierarchy from barons up their de jure liege's. (for EtB checking, in far future)
Added effect set_can_be_named_after_dynasty = no to suppress such naming for titles. You can also put can_be_named_after_dynasty = no in the title definition for historical titles (which means we solve that issue without editing the government file)

Dynamic descriptions now log when they make use of loc that does not exist (An error log of missing locals?is that what it is?)

Made several changes to the De Jure setup in Sub-Saharan Africa. 
Split up the much too big viking count north of Sweden in 1066 into smaller realms 
... Theres a lot more DeJure changes, which might affect our EtB sheet potentially, @Viridianus, Maybe you should redo it xP

Also no flags for flavorisations, Understandable, but disappointing

**Comment by Viridianus** [comment]
Only if I get the new redone localizations by the same script :D
I did not expect such a quick update, though :D

**Comment by Charanraja123** [comment]
Yeah I know, I could generate one for you after the update releases. Or did you want to wait for more patches to change it en masse or something?. It's your call.

**Comment by Viridianus** [comment]
No, no, we'll update EtB for 1.1, that's for sure (unless the version will turn out to be too bugged).

**Comment by Gr770** [comment]
-Added Saka culture to the Tarim Basin.
-Changed the names for a couple of duchies in eastern Germany. Ostmark is now named Nordmark, while previous Nordmark is named Mecklenburg (the Billung Mark).
- Updated and improved the Polabian setup, mainly in 867, and added a number of Polabian names for the area to have less German names under Polabian rule.

**Comment by Viridianus** [comment]
Saka does not seem to concern us as we already have such a column (it's in Iranian group), and I took care of Ostmark/Nordmark (and Wendish Empire). Their other map changes bother me more.

**Comment by Charanraja123** [comment]
@Viridianus How do you want the files
Do you want me to remove the initial special titles and those 4 empires you mentioned last time?

**Comment by Viridianus** [comment]
That sounds great (I've already went through the new special titles - they actually added one).

**Comment by Charanraja123** [comment]
Okay. In that case, I've uploaded them in the same GitHub repository. Check them out and let me know

**Comment by Viridianus** [comment]
OK. Note, though, that the bulk of their modifications seems to have been with cultural names.

**Comment by Charanraja123** [comment]
I can write stuff for that. But, I dont have a script ready. So it might take a while.
If it is something you can find useful. I can start working on it.

**Comment by Viridianus** [comment]
I'm going through 00_landed_titles anyway for title structure - csv was handy, but it is more opaque in this respect (no tabs, no brackets, only the letters e_ through b_ are some guidance), and it has those - so it is a possibility that I won't even be needing the new csv because all the changes I'll check anyway. Thus, if it's much work, don't bother, code stewards instead ;)

**Comment by Charanraja123** [comment]
The csv is structured in a way that every b_ is under the c_ but I understand its hard to read. But thats why there are different forms of the csv too which I have generated. There is a specific csv called landed_titles.csv which addresses recreates the structure in a more readable manner. Use whatever is comfortable to you.

**Comment by Charanraja123** [comment]
I do have a request tho. If you want me to write a script to generate the files, we need to include the localization(the e_, b_) as an additional column to make sure I can match stuff with paradox files or make sure you guys still have the same name in the first row as paradox vanilla game (harder since Paradox might change things each patch) for the same reason as matching it with vanilla. 
Obviously if you plan on including them in manually. All this doesn't matter.

**Comment by Viridianus** [comment]
You mean that you need a (hidden, I presume) column with codes of counties in EtB? Sounds deceptively easy.

**Comment by Charanraja123** [comment]
Yep. It should be easy in a sense, since we have a csv is the same order of the Etb sheet (I presume they werent any changes). But even if they were i also then assume you know most of them, an hidden or locked column with us only being able to edit it would be nice. It would allow me to not worry about changing names.

**Comment by Viridianus** [comment]
There were some de-jure layout changes, but I'll have to implement them anyway. As for locking - as we learned the hard way, locking prevents many restructuring operations AND (un)hiding.

**Comment by Charanraja123** [comment]
In that case just hide it. and ask people not to touch it.

**Comment by Gr770** [comment]
BTW if there is any major fixes, I'll be posting the new compatible file to steam this afternoon.

**Comment by Charanraja123** [comment]
Shittt.. I haven't played yet. Idk if I will lol, its been weeks since i played ck3.
Anyway, There shouldn't be any since we only have flavorisation files in the mod.
Also who is taking care of bookmarks? Its been there for a while now. Is it a modified one or just vanilla?

**Comment by Gr770** [comment]
It is modified. I changed the ruler titles.

**Comment by Charanraja123** [comment]
Oh okay. Cool. I didn't know.

**Comment by Gr770** [comment]
Its hard to notice. Lol.

**Comment by Charanraja123** [comment]
Holy shit did u guys check out the game
The bookmark page looks amazing now, Wow

**Comment by Viridianus** [comment]
Impressive - I wonder whether this will make bookmark editing more difficult though...

In EtB, I decided to be more careful with cultural names than before, so it goes more slowly, and I'll stop at k_pontus for now - I have life besides the mod (but note that d_socotra is already moved to its new non-titular position).

**Comment by Gr770** [comment]
There is no big changes to bookmark localization.

**Comment by Charanraja123** [comment]
This can also be closed, Since the patch didn't seem to affect our mod (as it is now) in any major way. Except of course slightly modifying the EtB sheet xP

**Comment by Viridianus** [comment]
Yep. While there seem to be some de-jure setup changes, I think it's nothing insurmountable.
