### ISSUE TITLE
Non-English localisations.

### ISSUE THREAD

**Issue by Charanraja123** [Gr770/CK3-Community-Title-Project#69]
This is a really bad look for us.

Our non-English localization do not work.
Every image below is from our Steam Release
![image](https://user-images.githubusercontent.com/16635399/94995188-43886400-05ba-11eb-8983-a3ee99a53d5b.png)
Above is German
![image](https://user-images.githubusercontent.com/16635399/94995210-76325c80-05ba-11eb-8dd9-8234935ee578.png)
Above is French
![image](https://user-images.githubusercontent.com/16635399/94995268-dc1ee400-05ba-11eb-8286-c594bc863aea.png)
Above is Spanish.

**Comment by Charanraja123** [comment]
@Gr770 or @Viridianus, One of you should definitely make a habit of atleast testing whether it works before either commiting or

**Comment by Gr770** [comment]
The new formatting never got copied over. I'll sent this as a fix update today. So the Master fixes will be renewed as well.

**Comment by Charanraja123** [comment]
Sure. How did we miss out on this?

**Comment by Gr770** [comment]
I'll leave a note for me to check all addition tags and the Master fix branch for latin scripting.

**Comment by Charanraja123** [comment]
Okay, I also think its weird that no one reported this.

**Comment by Viridianus** [comment]
Yeah, it's somewhat weird. Do we have an official list of supported languages in our mod?

**Comment by Charanraja123** [comment]
@Gr770 Did you check it before fixing?. It seems our steam German version is still broken

**Comment by Charanraja123** [comment]
I'll close this again
