### ISSUE TITLE
Font Update

### ISSUE THREAD

**Issue by Gr770** [Gr770/CK3-Community-Title-Project#85]
Looking for a 'map' like font

**Comment by Viridianus** [comment]
Map-like font which will also show all the symbols we need? Good forking luck. (Though I guess Charis SIL-SL looks more like map than usual Charis SIL.)

**Comment by Charanraja123** [comment]
Or maybe we remove the symbols which are problematic to us? I see it as a valid argument.

**Comment by Viridianus** [comment]
It is a... _valid_ position, to be sure, but I think that, if we can edit fonts, why not make use of it?

**Comment by Charanraja123** [comment]
People seem to love the paradox fonts, I really doubt any non-professional looking font can display all the letter we have used.

**Comment by Viridianus** [comment]
Well, there _is_ a third alternative, actually. It's just very... how do I put it, time-consuming and difficult. We can create a font.

**Comment by Charanraja123** [comment]
To be honest, If you guys do follow up on that, I mostly would not spend time on creating it. It feels like too much for too little.

**Comment by Viridianus** [comment]
Yeah, that might be too much. Well, we can continue searching for a good font which will also look good... maybe this?https://ctan.org/tex-archive/fonts/tipa/
And also - maybe even SIL fonts would be perceived better if we managed to make them bigger.

**Comment by Viridianus** [comment]
https://www.vulgarlang.com/ipafonts/ - we can go through these and think whether some of them are similar enough.

**Comment by Charanraja123** [comment]
> 
> And also - maybe even SIL fonts would be perceived better if we managed to make them bigger.

I tried to do that, But unfortunately there does not seem to a 'Size' arguments. So if you find anything let me know

**Comment by Charanraja123** [comment]
Map Font for reference 
![image](https://user-images.githubusercontent.com/16635399/95854691-e8eac700-0d74-11eb-8140-273e54ca8523.png)

**Comment by Charanraja123** [comment]
I do not think we will ever find one like that, It's too stylish looking for professional fonts.

**Comment by Charanraja123** [comment]
![image](https://user-images.githubusercontent.com/16635399/96081643-69293d80-0ed7-11eb-99d4-60e9ff8376b0.png)
https://www.vulgarlang.com/ipafonts/  This link, The bold one.

**Comment by Charanraja123** [comment]
![image](https://user-images.githubusercontent.com/16635399/96081855-d210b580-0ed7-11eb-9c4b-87295cb4e117.png)
https://www.vulgarlang.com/ipafonts/ This link, The Medium one

**Comment by Charanraja123** [comment]
![image](https://user-images.githubusercontent.com/16635399/96082090-3a5f9700-0ed8-11eb-87d0-7c545e77f7f8.png)
Default Map.

**Comment by Charanraja123** [comment]
If you look, you can see why changing the map font is off-putting to anyone. It's because PdX vanilla font only uses capital letters,

**Comment by Viridianus** [comment]
All-caps should be a manageable change... provided there is normal font manipulation, which there isn't.

**Comment by Charanraja123** [comment]
So its isn't a manageable change? xP. 
I also find it stupid that PdX used a only uppercase font, instead of converting everything to uppercase. 🦆

**Comment by Viridianus** [comment]
Well, it isn't that stupid - especially given they use a language with no string manipulation, but even regardless. It might be best to save only one string and use an all-caps font. And it wouldn't even be such a big problem if we didn't look for a font that's both all-caps and can manage our symbols.

**Comment by Charanraja123** [comment]
I think Jomini is the scripting language, I'm sure they have a coding language as a base underneath this (Mostly should be C, considering the games performance). They cannot develop a game with this language, 
On the bright side, we seemed to have found a pretty likeable one. Hopefully people don't give the same feedback this time

**Comment by Viridianus** [comment]
Even if it's C underneath, they buried it probably too deep for their own easy access, that's why they rarely expand their functions)

**Comment by Charanraja123** [comment]
Exactly why I called it stupid. 
Anyway enough of this.
