### ISSUE TITLE
Knight localization and '

### ISSUE THREAD

**Issue by Gr770** [Gr770/CK3-Community-Title-Project#90]
Currently
vityaz'
Wä'ali
Wä'aliyan
Aspetkʿ
Marc'heg
Marc'hegion
with apostrophes ʿ and '

**Comment by Gr770** [comment]
Might be a font issue as it only is affecting knights

**Comment by Charanraja123** [comment]
![image](https://user-images.githubusercontent.com/16635399/96103811-c207ce80-0ef5-11eb-809e-47e4b4738599.png)
Seems to be a font issue, let me check other apostrophes

**Comment by Charanraja123** [comment]
![image](https://user-images.githubusercontent.com/16635399/96104410-70ac0f00-0ef6-11eb-965d-14bc43d68376.png)
U+02B9 seems to work on normal font but not the title

**Comment by Charanraja123** [comment]
![image](https://user-images.githubusercontent.com/16635399/96104610-ae109c80-0ef6-11eb-9e9f-e3bad28cfebd.png)
U+2032 works for Everything

**Comment by Viridianus** [comment]
So, prime is inserted. Should we leave this issue as a reminder?

**Comment by Charanraja123** [comment]
I don't think so. It can be closed
