### ISSUE TITLE
Wales Lordship and County Priority.

### ISSUE THREAD

**Issue by Gr770** [Gr770/CK3-Community-Title-Project#93]
New county base priority needs to be 20 to over write the lordship of wales flavour.
Manual overwrite does not work.

**Comment by Charanraja123** [comment]
I leave a comment here, similar to one left in Pull request. 

Raising the base priority to 19 (Actual value) is no problem at all. We just have to make sure we do not give the same priority to cultural groups and cultures. There are also independent cultural groups which override cultures and should have priority as such. 
Once We've checked these, it can be merged
